name: learn-github-actions
on: [push]
jobs:
  'prove-lrt':
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: 'echo "hello abcd"'
